### ISSUE TITLE
node-icu-charset-detectorがローカルにインストールされていないとnode-gyp関連のエラーでビルドできない

### ISSUE THREAD

**Issue by ytanaka-** [nikezono/unific#50]
readmeの通りではビルドできなかったので、一応issue立てておきます。

https://github.com/mooz/node-icu-charset-detector/issues/7
と同じエラーが発生したんですけど
https://github.com/mooz/node-icu-charset-detector
をインストールしたらビルドできました。

**Comment by nikezono** [comment]
sorry.
それはhttps://github.com/nikezono/node-find-rss
の依存関係です。

こちらのモジュールのインストール時に `livicu-dev` か `icu4c`をインストールするようにします。
