### ISSUE TITLE
記事横にブログ名が表示されないことがある

### ISSUE THREAD

**Issue by sota1235** [nikezono/unific#82]
DJあおいの記事が"RSS"と表記されてるのでブログ名を出して欲しい

![pic](http://i.gyazo.com/15a3184391281fd4f8404b2b66af3b9f.png)

**Comment by sota1235** [comment]
です

**Comment by nikezono** [comment]
https://github.com/nikezono/node-find-rss/issues/12

と関連

**Comment by nikezono** [comment]
![gyazo](http://gyazo.com/7717e3ca5eb37c6bfcfa698cb556015b.png)

どうすか

**Comment by sota1235** [comment]
めっちゃよいです！！！

**Comment by nikezono** [comment]
ありがとう
